### ISSUE TITLE
Danger option on checklist

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#48]
Currently it blocks the checklist from being submitted. @markstreaka thinks this needs to be submittable with some sort of flow that takes it into account.

**Comment by markstreaka** [comment]
When Danger is selected a popup shows: "You have selected "Danger" for this item. Please report this problem to the relevant person(s) immediately and ensure this piece of equipment is not used until the issue is resolved." - Plus an "Acknowledged" button that is required.

Then again at completion of the checklist another popup appears saying "You have selected "Danger" for one or more items in this checklist. Please report this problem to the relevant person(s) immediately and ensure this piece of equipment is not used until the issue is resolved." - Plus an "Acknowledged" tick box  that is required before "submit" button can be pressed.

**Comment by jpike88** [comment]
no problem, we'll do that. looks good to me

**Comment by alexkingma1** [comment]
- [ ] test
